import org.gradle.api.JavaVersion

object Versions {
    const val kotlinVersion = "1.6.20"
    const val kotlinDateTimeVersion = "0.3.2"
    const val kotlinCoroutinesVersion = "1.6.0"
    const val coreKtxVersion = "1.7.0"
    const val appCompatVersion = "1.4.0"
    const val materialDesignVersion = "1.5.0"
    const val constraintLayoutVersion = "2.1.3"
    const val legacySupportVersion = "1.0.0"
    const val hiltVersion = "2.38.1"
    const val navVersion = "2.4.1"
    const val lifecycleVersion = "2.4.1"
    const val pagingVersion = "3.1.1"
    const val fragmentKtxVersion = "1.4.1"
    const val securityVersion = "1.0.0"
    const val coroutinesAndroidVersion = "1.6.0"
    const val roomVersion = "2.4.1"
    const val recyclerView = "1.2.1"
    const val junit = "1.1.3"
    const val cardviewVersion = "1.0.0"

    const val gradleVersion = "7.2.1"
    const val ktlintVersion = "10.2.0"
    const val googleServiceVersion = "4.3.10"
    const val playCoreVersion = "1.10.0"

    const val lottieVersion = "3.6.0"
    const val firebaseBomVersion = "29.3.0"
    const val firebaseMessagingVersion = "22.0.0"
    const val viewPagerIndicatorVersion = "4.1.2"
    const val glideVersion = "4.13.0"
    const val retrofitVersion = "2.9.0"
    const val okHttpVersion = "4.9.3"
    const val coilVersion = "1.4.0"
    const val kotlinxSerializationConverterVersion = "0.8.0"
    const val junitVersion = "4.13.2"
    const val espressoVersion = "3.4.0"
    const val androidTestVersion = "1.1.3"
    const val ossPluginVersion = "0.10.4"
    const val ossVersion = "17.0.0"
    const val timberVersion = "4.7.1"
    const val flipperVersion = "0.100.0"
    const val soloaderVersion = "0.10.1"
    const val leakCanaryVersion = "2.6"
    const val kotlinxSerializationJsonVersion = "1.2.2"
    const val gsonVersion = "2.8.9"
    const val gsonConverterVersion = "2.9.0"
    const val naverAuth = "5.1.0"

    val javaVersion = JavaVersion.VERSION_11
    const val jvmVersion = "11"
}
