import org.gradle.api.JavaVersion

object Versions {
    const val kotlinVersion = "1.8.0"
    const val kotlinCoroutinesVersion = "1.5.0"
    const val coreKtxVersion = "1.7.0"
    const val appCompatVersion = "1.4.2"
    const val materialDesignVersion = "1.7.0"
    const val constraintLayoutVersion = "2.1.3"
    const val legacySupportVersion = "1.0.0"
    const val hiltVersion = "2.42"
    const val navVersion = "2.5.0"
    const val lifecycleVersion = "2.4.1"
    const val fragmentKtxVersion = "1.4.1"
    const val securityVersion = "1.0.0"
    const val coroutinesAndroidVersion = "1.3.9"
    const val recyclerView = "1.2.1"
    const val junit = "1.1.3"
    const val cardviewVersion = "1.0.0"
    const val emoji = "1.1.0"
    const val flexBoxVersion = "3.0.0"
    const val window = "1.0.0"
    const val multiIndex = "2.0.1"

    const val lottieVersion = "3.6.0"
    const val glideVersion = "4.13.0"
    const val retrofitVersion = "2.9.0"
    const val okHttpVersion = "4.9.3"
    const val coilVersion = "1.4.0"
    const val kotlinxSerializationConverterVersion = "0.8.0"
    const val junitVersion = "4.13.2"
    const val espressoVersion = "3.4.0"
    const val androidTestVersion = "1.1.3"
    const val timberVersion = "4.7.1"
    const val kotlinxSerializationJsonVersion = "1.3.2"
    const val gsonVersion = "2.8.9"
    const val gsonConverterVersion = "2.9.0"
    const val dataStore = "1.0.0"
    const val protoBuf = "3.18.0"
    const val roomVersion = "2.4.2"
    const val paging = "3.1.1"

    val javaVersion = JavaVersion.VERSION_17

    const val mockitoCoreVersion = "2.28.2"
    const val mockitoAndroidVersion = "2.24.5"
    const val googleServiceVersion = "4.3.15"
    const val firebasePlatformVersion = "32.1.1"
    const val firebaseCrashlyticsGradleVersion = "2.9.5"
    const val kakaoVersion = "2.12.1"
    const val dotsIndicator = "4.3"
}
