# This is a basic workflow to help you get started with Actions

name: MumentAndroidCI

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Decode BASE_URL
        env:
          BASE_URL: ${ secrets.BASE_URL }
        run: echo BASE_URL=\"$BASE_URL\" > ./local.properties
          
      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Change gradlew permissions
        run: chmod +x ./gradlew

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      - name: Build APK
        run: bash ./gradlew assembleRelease --stacktrace
        
      - run: './gradlew assembleRelease'
      - uses: MeilCli/slack-upload-file@v1
        with:
          slack_token: ${{ secrets.SLACK_READ_WRITE_TOKEN }}
          channels: ${{ secrets.SLACK_CHANNEL_DEPLOY }}
          file_path: 'app/build/outputs/apk/release/app-release-unsigned.apk'
          file_name: 'app-release-unsigned.apk'
          file_type: 'apk'
          initial_comment: '${{ github.ref }} Success Deploy Mument App'
          
      - name: Mument apk artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release-unsigned.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
          
      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Notify Build
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
